[[navbar]]
identifier = "project"
name = "project"
title = "project"
url = "/project/"
weight = 2
[[navbar]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 3
[[navbar]]
identifier = "blog"
name = "blog"
title = "blog"
url = "https://blog.anhgelus.world"
weight = 4
[[navbar]]
identifier = "contact"
name = "contact"
title = "contact"
url = "/contact/"
weight = 5
[[navbar]]
identifier = "terms"
name = "terms of use"
title = "terms of use"
url = "/terms/"
weight = 100 
